<?php
/*BEGIN_INFO
Fake search results by WScripts.net
END_INFO*/
if(!defined("WCDDL_GUTS"))
   exit;
$q = strip_tags($_REQUEST['q']);
$qlink = str_replace(" ", "+", ucwords($q));

$fakeresults=array(
'<tr><td class="ttype"><span class="home">New</span></td><td class="ttitl"><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="'.ucwords($q).' Free Download" target="_blank" rel="nofollow">'.ucwords($q).' Free Download</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.undernation.com/in.php?id=ddl0" title="Downloads Provided by Undernation" rel="nofollow">Undernation</a></td></tr>',
'<tr><td class="ttype"><span class="home">Full</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="'.$q.' [2009]" target="_blank" rel="nofollow">'.$q.' [2009]</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.undernation.com/in.php?id=ddl0" title="Downloads Provided by Undernation" rel="nofollow">Undernation</a></td></tr>',
'<tr><td class="ttype"><span class="home">Newest</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="[NEW] '.ucwords($q).'" target="_blank" rel="nofollow">[NEW] '.ucwords($q).'</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.undernation.com/in.php?id=ddl0" title="Downloads Provided by Undernation" rel="nofollow">Undernation</a></td></tr>',
'<tr><td class="ttype"><span class="home">Full</span></td><td class="ttitl"><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="[2010] '.ucwords($q).' Fast" target="_blank" rel="nofollow">[2010] '.ucwords($q).' Fast</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.undernation.com/in.php?id=ddl0" title="Downloads Provided by Undernation" rel="nofollow">Undernation</a></td></tr>',
'<tr><td class="ttype"><span class="home">Full</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="'.ucwords($q).' Full" target="_blank" rel="nofollow">'.ucwords($q).' Full</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://wareztoplist.com/in.php?id=ddl0" title="Downloads Provided by WarezTop" rel="nofollow">WarezTop</a></td></tr>',
'<tr><td class="ttype"><span class="home">Latest</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="'.ucwords($q).' Official" target="_blank" rel="nofollow">'.ucwords($q).' Official</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://wareztoplist.com/in.php?id=ddl0" title="Downloads Provided by WarezTop" rel="nofollow">WarezTop</a></td></tr>',
'<tr><td class="ttype"><span class="home">Trusted</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="'.ucwords($q).' ViViD Release" target="_blank" rel="nofollow">'.ucwords($q).' ViViD Release</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://wareztoplist.com/in.php?id=ddl0" title="Downloads Provided by WarezTop" rel="nofollow">WarezTop</a></td></tr>',
'<tr><td class="ttype"><span class="home">Latest</span></td><td class="ttitl"><span title="Netload Links" class="thost">NL</span><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/special-offer.cfm?ap_id=11670" title="Full '.ucwords($q).'" target="_blank" rel="nofollow">Full '.ucwords($q).'</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://wareztoplist.com/in.php?id=ddl0" title="Downloads Provided by WarezTop" rel="nofollow">WarezTop</a></td></tr>',
'<tr><td class="ttype"><span class="home">Newest</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="'.ucwords($q).' New Release" target="_blank" rel="nofollow">'.ucwords($q).' New Release</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://ddl2.com/in.php?id=ddl0" title="Downloads Provided by DDL2" rel="nofollow">DDL Two</a></td></tr>',
'<tr><td class="ttype"><span class="home">Working</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="Trusted '.ucwords($q).' Download" target="_blank" rel="nofollow">Trusted '.ucwords($q).' Download</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://ddl2.com/in.php?id=ddl0" title="Downloads Provided by DDL2" rel="nofollow">DDL Two</a></td></tr>',
'<tr><td class="ttype"><span class="home">New</span></td><td class="ttitl"><span title="Netload Links" class="thost">NL</span><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="'.ucwords($q).' (2010) Full" target="_blank" rel="nofollow">'.ucwords($q).' (2010) Full</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://ddl2.com/in.php?id=ddl0" title="Downloads Provided by DDL2" rel="nofollow">DDL Two</a></td></tr>',
'<tr><td class="ttype"><span class="home">Trusted</span></td><td class="ttitl"><span title="FileFactory Links" class="thost">FF</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="'.ucwords($q).' V2 Working" target="_blank" rel="nofollow">'.ucwords($q).' V2 Working</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.warez-downloads.net/in.php?id=ddl0" title="Downloads Provided by Warez Downloads" rel="nofollow">Warez Downloads</a></td></tr>',
'<tr><td class="ttype"><span class="home">Latest</span></td><td class="ttitl"><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="'.ucwords($q).' V2 Working" target="_blank" rel="nofollow">'.ucwords($q).' </a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.warez-downloads.net/in.php?id=ddl0" title="Downloads Provided by Warez Downloads" rel="nofollow">Warez Downloads</a></td></tr>',
'<tr><td class="ttype"><span class="home">New</span></td><td class="ttitl"><span title="Storage Links" class="thost">ST</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="'.ucwords($q).' Latest" target="_blank" rel="nofollow">'.ucwords($q).' Latest</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.downloadwarez.org/in.php?id=ddl0" title="Downloads Provided by DownloadWarez" rel="nofollow">DownloadWarez</a></td></tr>',
'<tr><td class="ttype"><span class="home">Working</span></td><td class="ttitl"><span title="N/A" class="thost">N/A</span> <a href="http://www.binverse.com/bnv/DownloadNow-signup.cfm?ap_id=11675" title="[TRUSTED] '.ucwords($q).'" target="_blank" rel="nofollow">[TRUSTED] '.ucwords($q).' Latest</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.downloadwarez.org/in.php?id=ddl0" title="Downloads Provided by DownloadWarez" rel="nofollow">DownloadWarez</a></td></tr>',
'<tr><td class="ttype"><span class="home">Latest</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="(Fast) '.ucwords($q).'" target="_blank" rel="nofollow">(Fast) '.ucwords($q).' Latest</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.downloadwarez.org/in.php?id=ddl0" title="Downloads Provided by DownloadWarez" rel="nofollow">DownloadWarez</a></td></tr>',
'<tr><td class="ttype"><span class="home">Direct</span></td><td class="ttitl"><span title="FileFactoy Links" class="thost">FF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="[DIRECT] '.strtolower($q).' download" target="_blank" rel="nofollow">[DIRECT] '.strtolower($q).' dowload</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.warezomen.com/in.php?id=ddl0" title="Downloads Provided by WarezOmen" rel="nofollow">WarezOmen</a></td></tr>',
'<tr><td class="ttype"><span class="home">Latest</span></td><td class="ttitl"><span title="Netload Links" class="thost">NL</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="'.ucwords($q).' Single Link" target="_blank" rel="nofollow">'.ucwords($q).' Single Link</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate4">4</div> <a href="http://www.warezomen.com/in.php?id=ddl0" title="Downloads Provided by WarezOmen" rel="nofollow">WarezOmen</a></td></tr>',
'<tr><td class="ttype"><span class="home">Working</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="'.strtolower($q).' - working" target="_blank" rel="nofollow">'.strtolower($q).' - working</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://www.warezworm.com/in.php?id=ddl0" title="Downloads Provided by WarezWorm" rel="nofollow">WarezWorm</a></td></tr>',
'<tr><td class="ttype"><span class="home">Trusted</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="HotFile Links" class="thost">HF</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="Latest '.$q.' NEW" target="_blank" rel="nofollow">Latest '.$q.' NEW</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://www.warezworm.com/in.php?id=ddl0" title="Downloads Provided by WarezWorm" rel="nofollow">WarezWorm</a></td></tr>',
'<tr><td class="ttype"><span class="home">Full</span></td><td class="ttitl"><span title="FileServe Links" class="thost">FS</span><span title="RapidShare Links" class="thost">RS</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="'.ucwords($q).' Latest" target="_blank" rel="nofollow">'.ucwords($q).' Latest</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://www.warezworm.com/in.php?id=ddl0" title="Downloads Provided by WarezWorm" rel="nofollow">WarezWorm</a></td></tr>',
'<tr><td class="ttype"><span class="home">Working</span></td><td class="ttitl"><span title="HotFile Links" class="thost">HF</span><span title="Megaupload Links" class="thost">MU</span> <a href="http://www.binverse.com/BNV/usenet-downloads.cfm?ap_id=11672" title="'.ucwords($q).' (Updated)" target="_blank" rel="nofollow">'.ucwords($q).' (Updated)</a></td><td class="tdate">Today</td><td class="tprov"><div class="trate5">5</div> <a href="http://www.warezworm.com/in.php?id=ddl0" title="Downloads Provided by WarezWorm" rel="nofollow">WarezWorm</a></td></tr>',
);

function fakeresults() {
	$faker='';
	if($_GET['q']!=NULL) {
		global $core,$downloads,$fakeresults;
		if(count($downloads)<='10') {
			shuffle($fakeresults);
			$r=rand(2,5);
			for($i=0;$i<$r;$i++) {
				//$c=count($fakeresults);
				//$r=rand(0,$c);
				$faker=$faker.$fakeresults[$i];
			}
			$core->setTemplateVar("fakeresults",$faker);
		}
		elseif(count($downloads)>'10') {
			shuffle($fakeresults);
			$faker=$fakeresults['0'];
			$core->setTemplateVar("fakeresults",$faker);
		}
	}
}


?>